---
- name: Install golang
  apt: name=golang

- name: Compile cli53
  command: go get github.com/barnybug/cli53/cmd/cli53
  environment:
      GOPATH: /home/ubuntu/go
  remote_user: ubuntu

- name: Install cli53
  copy:
      remote_src: yes
      src: /home/ubuntu/go/bin/cli53
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 755

# optional: remove golang
