---
- name: jenkins_smc_sync_config_path is undefined, defaulting to {{ config_path }}/config
  set_fact: jenkins_smc_sync_config_path={{ config_path }}/config
  when: jenkins_smc_sync_config_path is not defined

- name: Copy custom configuration files
  copy:
    src="{{ item }}"
    dest="{{ jenkins_directory }}/"
    owner=jenkins
    group=jenkins
  with_fileglob:
    - "{{ jenkins_smc_sync_config_path }}/*.xml"
  notify: reload jenkins
