---
- name: Install Jenkins plugins
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:8080/ -i {{ jenkins_directory }}/.ssh/id_rsa install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins
  
- name: Install custom Jenkins plugins
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:8080/ -i {{ jenkins_directory }}/.ssh/id_rsa install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: "{{ jenkins_custom_plugins }}"
  notify: restart jenkins
